#!/usr/bin/expect -f

set timeout 10
set ip [lindex $argv 0]
set protocol [lindex $argv 1]
set port [lindex $argv 2]
set test_file [lindex $argv 3]

# Démarrage du client
spawn ./client $ip $protocol $port

# Attendre le prompt de choix de source
expect "■ Data source?"
send "2\r"  # Choix fichier

expect "File name:"
send "$test_file\r"

# Attendre le résultat
expect {
    "=== RESULT *===" {
        puts "\n✅ Test succeed"
        expect eof
        exit 0
    }
    timeout {
        puts "\n❌ Timeout - no response"
        exit 1
    }
    "Error:*" {
        puts "\n❌ Error détected"
        exit 1
    }
}
